name = "discord-oidc"
main = "worker.js"
compatibility_date = "2022-12-24"

kv_namespaces = [
  { binding = "KV", id = "1a1e202ced394de9b95d6f6e089d9256", preview_id = "b43c22430b5240dea89cd6cc350d3946" }
]